### ISSUE TITLE
What's the history of this project since 2006, and why is the latest release on PECL a decade out of date?

### ISSUE THREAD

**Issue by ExplodingCabbage** [zenovich/runkit#89]
I've never used Runkit in the past, but I've been aware of its existence through seeing it in the PHP manual. What I never realised, until reading [your comment on a recent Stack Overflow post of mine](http://stackoverflow.com/questions/29056248/objective-c-categories-equivalent-in-php#comment53255993_30699315), was that [the version of the library hosted on PECL](http://pecl.php.net/package/runkit) hasn't had a release since 2006 while development here has proceeded. I also see that the docs on php.net are out of date with regards to your fork - for instance, they don't mention the new ability to pass function definitions as closures.

I [also see](http://git.php.net/?p=pecl/php/runkit.git;a=summary) that the PECL version of the library has still undergone some development by Sara Golemon as recently as this year, albeit without a new release version.

How come these two forks exist in parallel? What differences exist between them? Do you have any plans to officially take over the project, including the PECL package? What would be necessary to do that?

I'd be happy to help out in any way I can with bringing the PECL package and php.net docs up to date, but it'd be helpful to understand the situation first - there's nothing in the readme here or in the docs that even acknowledges that this library has two parallel forks, let alone addresses why.

**Comment by klonos** [comment]
@ExplodingCabbage you might be interested in #51

**Comment by zenovich** [comment]
Runkit was authored in 2005 by Sara Golemon. The last release she made was v0.9 (06.06.06). After that she abandoned maintenance of Runkit, so the project was left till 2009.

In 2009 I started maintaining Runkit here on github. Since then four versions have been released (see full changelog in package.xml file) excluding dummy release v.1.0.0.

I know that in 2013 Sara decided to spend some time (frankly a few days) on Runkit and fixed some issues from bugs.php.net. Probably she didn't know about my work. After she has been informed, some merges were made not always indicating authoring. She also made some work on project then. Later PHP5.7 support has been made and undone.

The difference between two projects is a bigger part of all I did here. A thorough analysis is needed to get details, but superficially by applying tests to pecl project I get this list:

Missing functionality
•	Can’t add functions/methods with doc-comments
•	Can’t add closures as functions/methods
•	Can’t set doc-comments for redefined functions/methods
•	Can’t redefine functions/methods by closures
•	Can’t add methods with doc-comments
•	Added or redefined functions/methods can’t return reference
•	No runkit_default_property_remove() function
•	No RUNKIT_OVERRIDE_OBJECTS constant and no related functionality, doesn’t touch objects at all (leads to segfaults).
•	runkit_default_property_add() can’t add non-scalar default values for properties
•	Properties names are still case-insensitive
•	__debugInfo magic method can’t be properly overridden
•	PHP4-style constructors are not inherited by subclasses on adding/copying/redefining
•	PHP4-style constructors are not inherited by subclasses on class adopting
•	PHP4-style constructors don’t work after importing and are not inherited by subclasses
•	Functions runkit_class_adopt & runkit_class_emancipate don’t change class-hierarchy (issue #13)
•	Cannot apply closure to a sandbox via call_user_func()
Bugs and crashes
•	Runkit_Sandbox::echo() leads to a segmentation fault
•	Incorrectly parses open_basedir INI-setting with several paths in Windows
•	Crash after using runkit_class_adopt when accessing inherited properties of the parent class inside methods (issue #59)
•	Namespaces are not fully supported by constants manipulation functions
•	Accessing dynamically added properties of objects that have been already created leads to segmentation faults
•	Internal functions renaming leads to segmentation faults
•	PHP5.4+ run_time_cache is not cleared, so calling of modified functions and methods leads to segmentation faults
•	Can’t import properties with constant array values
•	Can’t import properties that have been modified via reflection
•	Can’t override private and protected properties on import
•	Added or redefined non-static methods can’t be called statically
•	Can't add or rename a method that will override a parent method (issue #62)
•	Accessing added private and protected properties from methods of the same class leads to segmentation faults
•	Removes user functions too early (issue #70)

**Comment by zenovich** [comment]
Documentation on php.net and releases on pecl.php.net are administred by the maintainer of the extension. I have no rights for this.

I wrote Sara several times but she ignores questions about changing maintainer. I think the reason is that Runkit is her project and she doesn't want to give it up.

I hope Sara reads this and can also give a comment.

**Comment by zenovich** [comment]
Documentation on php.net and releases on pecl.php.net are administred by the maintainer of the extension. I have no rights for this.

I wrote Sara several times but she ignores questions about changing maintainer. I think the reason is that Runkit is her project and she doesn't want to give it up.

I hope @sgolemon reads this and can also give a comment.

**Comment by HallofFamer** [comment]
Yeah I hope @sgolemon will see this too. Its better to port the latest version of runkit to PECL, rather than the outdated version. It's the voice from us users of this extension.

**Comment by ExplodingCabbage** [comment]
I don't know enough of the details of the project to say with certainty that Dmitry's version should take over on PECL, but it certainly looks that way at a glance. @sgolemon, can you weigh in?

**Comment by HallofFamer** [comment]
@sgolemon 
Several days have passed, any words on this?

**Comment by HallofFamer** [comment]
@sgolemon 
Still no explanation? We very appreciate your early work of runkit, without you it wouldnt be where it is now. However, you need you to step down and acknowledge that you are not a suitable maintainer of runkit anymore. Runkits need to continue to evolve, and we need dedicate developers. I hope you understand this, and your name will always be credited as the creator of runkit, even if you are not maintaining it any longer. Thank you.

**Comment by zenovich** [comment]
http://zenovich.blogspot.ru/2015/10/runkit-1.0.4.html

**Comment by HallofFamer** [comment]
@sgolemon
Still no comment?

**Comment by zenovich** [comment]
http://zenovich.blogspot.ru/2015/10/video-of-runkits-evolution.html

**Comment by ExplodingCabbage** [comment]
Somebody should probably reach out to @sgolemon via some other medium in case she has GitHub @-notifications off or something. I'll hit her up on Twitter.

**Comment by HallofFamer** [comment]
@ExplodingCabbage 
I see, this is understandable. Anyway, its time to change ownership of runkit now.

**Comment by sgolemon** [comment]
Hey, @zenovich!   @ExplodingCabbage is right, I'm not ignoring you, I just don't use github notifications (and email's signal to noise ratio is so absurdly low it's not worth laughing at).

  1. You're absolutely right that I don't maintain runkit.  You clearly do.
  2. Yep, initially in 2013 I updated the official runkit repo to work with newer versions before being told about zenovich/runkit, and I merged in a bunch of tests (with attribution, I thought.  Perhaps I mised a couple commits) and wrote my own fixes to make them work (I actually recall disagreeing on the method of fix for a few of them).
  3. If you want to take over the official project, go for it.  I'm happy enough to give it up to someone who'll take care of it.  I think I recall telling you this in an email a couple years ago, I could be imaging that...
    1. Do you have phpdoc karma alreay?  Because indidivudal sections of the manual aren't restricted to project owners, anyof the 1000 or so people with phpdoc karma can update any manual page.
    2. You'll need to talk to a PECL admin about gaining ownership of the runkit package on PECL.  *Point them at this comment as my official go-ahead.*
    3. I'd recommend archiving github.com/php/pecl-php-runkit by making a tag/branch for it (called `archive` or whatever), and adding a delete commit to `master` taking out the old version and explaining that yours is the official source.  Do you want me to just do that now since I already have src karma for that?  Note that I'll have a fork of the current git.php.net version on my github just in case the old one gets deleted.  Because backups...

**Comment by sgolemon** [comment]
https://github.com/sgolemon/archive-runkit  <--- Will push that up to git.php.net / github.com/php/pecl-php-runkit if it looks good

**Comment by sgolemon** [comment]
Oh, and because turnabout is fair play: https://github.com/zenovich/runkit/blob/master/LICENSE  <--- The original project was BSD licensed which requires attribution.  Mind adding a line with my name?

**Comment by sgolemon** [comment]
Here's an easy PR for ya: https://github.com/zenovich/runkit/pull/92

**Comment by sgolemon** [comment]
Pushed: https://github.com/php/pecl-php-runkit  Runkit is your problem now. :)

**Comment by klonos** [comment]
@sgolemon :+1: :heart: Thanx!

**Comment by zenovich** [comment]
@sgolemon Thanks a lot!

**Comment by HallofFamer** [comment]
@sgolemon 
Thats really good news, thanks. With this, runkit's new version will be on PECL soon.

**Comment by IngwiePhoenix** [comment]
@sgolemon @zenovich 
Amazing! I was worried I'd have to find an alternative way to get around a few things that were only possible through runkit - but seeing that maintenance has picked up again on it AND it is going to be "offical" again, is pretty awesome!

Thanks for your work, both of you. You totally made my day (and my happyness-expressing yell probably tore my friend's ears off... oh well).

**Comment by sgolemon** [comment]
https://pecl.php.net/package/runkit

^ Guess who's listed as a lead maintainer now (Thanks to bjori )

**Comment by zenovich** [comment]
Thanks! All releases have been reissued on pecl!

**Comment by HallofFamer** [comment]
This is great, runkit on PECL now. Maybe add these windows .dll too?
https://github.com/Crack/runkit-windows

**Comment by IngwiePhoenix** [comment]
@sgolemon Awesome. :) Thanks for the notice, although I got a lot of emails from PECL already, announcing the new runkit releases.

**Comment by zenovich** [comment]
@HallofFamer sure, but I don't know how to do it.

**Comment by klonos** [comment]
Awesome!! :clap:
