### ISSUE TITLE
Unable to modify namespaced functions

### ISSUE THREAD

**Issue by chazmuzz** [zenovich/runkit#90]
I'm not able to redefine a function that was declared inside of a namespace.  I see that namespaces.phpt has tests for modifying methods inside of namespaced classes.  But since there are no tests for modifying a namespaced function I assume that this has not been implemented yet. 

Are there any plans to add/fix this functionality?

```
Original Testme Implementation
PHP Parse error:  syntax error, unexpected '\' (T_NS_SEPARATOR), expecting '(' in /testme.php(9) : runkit created function on line 1
PHP Stack trace:
PHP   1. {main}() /testme.php:0
PHP   2. runkit_function_redefine() /testme.php:9
```

```php
<?php

namespace Foo;

function testme() {
  echo "Original Testme Implementation\n";
}
testme();
runkit_function_redefine('Foo\testme','','echo "New Testme Implementation\n";');
testme();
```

**Comment by TysonAndre** [comment]
You're using an outdated version of runkit. He fixed this in 2012.
https://github.com/zenovich/runkit/blob/master/tests/namespaces.phpt

Instructions for installing the latest release: https://github.com/zenovich/runkit#building-and-installing-latest-release-with-pecl-in-unix

**Comment by zenovich** [comment]
Exactly :+1:

**Comment by TysonAndre** [comment]
The provided example code worked as expected with the most recent runkit.

However, I noticed a bug/inconsistency when writing a test case for modifying namespaced functions (Currently, there are only tests of namespaced *methods*):
Runkit's function manipulation works properly for functions with no leading "\", but doesn't work when there is a leading "\"

Because method manipulation works properly for namespaced classes with leading "\"es, I think that runkit should handle namespaced functions the same way.

https://github.com/zenovich/runkit/pull/91

**Comment by chazmuzz** [comment]
Ooops! I installed runkit using homebrew.  The homebrew version is over a year out of date.  I'll take my problem there instead.  Thanks
